project:
  type: website
  output-dir: rendered-output

website:
  title: "companyname"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: "https://github.com/companyname/"
        aria-label: GitHub
    contents:
      - href: index.ipynb
        text: Project Overview

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
